ss={name:"Darren",sex:"male",address:{sheng:"SiChuan",shi:"Chengdu"}}
ss1=JSON.stringify(ss);
ss2=JSON.parse(ss1);
ss3=Object.assign({},ss);//浅克隆，为指针的属性只是把指针克隆过去
console.log(ss);
console.log(ss1);
console.log(ss2);
console.log(ss3);
ss3.address.shi="SuiNing";
console.log(ss);